const ACTION_TYPES = {
    ADD_EMPLOYEE: "ADD_EMPLOYEE",
    GET_EMPLOYEES: "GET_EMPLOYEES",
    GET_EMPLOYEE: "GET_EMPLOYEE",
    UPDATE_EMPLOYEE: "UPDATE_EMPLOYEE",
    DELETE_EMPLOYEE: "DELETE_EMPLOYEE",
  };
  
  export default ACTION_TYPES;
  