const ACTION_TYPES = {
    ADD_DEPARTMENT: "ADD_DEPARTMENT",
    GET_DEPARTMENTS: "GET_DEPARTMENTS",
    GET_DEPARTMENT: "GET_DEPARTMENT",
    UPDATE_DEPARTMENT: "UPDATE_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
  };
  
  export default ACTION_TYPES;
  